### ISSUE TITLE
Issue after updating to latest version

### ISSUE THREAD

**Issue by abhishekkaura** [xvik/dropwizard-guicey#252]
Hi, My application is failing to start after upgrading to latest version and working fine with 4.2.2 version

Initialize method

@OverRide
public void initialize(Bootstrap bootstrap) {
final Config config = ConfigFactory.load();
bootstrap.setConfigurationSourceProvider(new FileConfigurationSourceProvider());
bootstrap.addBundle(GuiceBundle.builder()
.enableAutoConfig("com.test.platform.audience",
"com.test.platform.connectors.rest")
.modules(new AppModule())
.modules(new HttpClientModule())
.modules(new SerializationModule())
.modules(TypesafeConfigModule.fromConfigWithPackage(config, "com.test.platform.audience"))
.searchCommands()
.build());
}

Exception in thread "main" java.lang.NoClassDefFoundError: org/glassfish/jersey/server/internal/inject/AbstractValueFactoryProvider at java.base/java.lang.ClassLoader.defineClass1(Native Method) at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016) at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800) at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698) at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621) at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) at java.base/java.lang.Class.forName0(Native Method) at java.base/java.lang.Class.forName(Class.java:398) at ru.vyarus.dropwizard.guice.module.installer.scanner.util.OReflectionHelper.getClassesFor(OReflectionHelper.java:55) at ru.vyarus.dropwizard.guice.module.installer.scanner.ClasspathScanner.performScan(ClasspathScanner.java:108) at ru.vyarus.dropwizard.guice.module.installer.scanner.ClasspathScanner.<init>(ClasspathScanner.java:50) at ru.vyarus.dropwizard.guice.module.GuiceyInitializer.<init>(GuiceyInitializer.java:77) at ru.vyarus.dropwizard.guice.GuiceBundle.initialize(GuiceBundle.java:116) at io.dropwizard.setup.Bootstrap.addBundle(Bootstrap.java:150) at com.test.platform.audience.application.TestService.initialize(TestService.java:84) at io.dropwizard.Application.run(Application.java:88) at com.test.platform.audience.Main.main(Main.java:35) Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.server.internal.inject.AbstractValueFactoryProvider at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 20 more

**Comment by xvik** [comment]
Hi! 4.2.2 was working with dropwizard 1.3 and 5.x works with dropwizard 2.x. There were some breaking changes in dropwizard 2 and one of them is removal of `AbstractValueFactoryProvider` class. Instead, `org.glassfish.jersey.server.internal.inject.AbstractValueParamProvider` should be used.

See [5.0 migration guide](http://xvik.github.io/dropwizard-guicey/5.0.0/about/release-notes/#migration-guide) it should mention all such cases (and all guicey-related changes). Also, here is [dropwizard migration guide](https://www.dropwizard.io/en/release-2.0.x/manual/upgrade-notes/upgrade-notes-2_0_x.html)

**Comment by krutsko** [comment]
Sorry for intervention with a side-question.

We are using DW 1.3 and Guicey 4.2.2 with Java 11, and now going to upgrade it to Java 17, so we had to upgrade Guice to 5.x (without updating DW to 2.x and Guicey to 5.x).

@xvik Do you see any compatibility issues here: **DW 1.3.x** and **Guicey 4.2.2** and **Guice 5.0.1** and **Java 17**.

Thank you!

**Comment by xvik** [comment]
> Do you see any compatibility issues here: DW 1.3.x and Guicey 4.2.2 and Guice 5.0.1 and Java 17.

Yes, there would be one problem: in guice 5 one internal class was renamed and I used it directly (internall stopwatch) so, most likely, there would ClassNotFoundException on startup ([this one](https://github.com/xvik/dropwizard-guicey/issues/187)). 
It was properly fixed only in 5.4.1

I was asking if someone needs [4.2.4 release](https://github.com/xvik/dropwizard-guicey/discussions/183) but noone reacted on this (but probably you are not affected with these exact issues).

There was also a [4.2.3 version released](https://xvik.github.io/dropwizard-guicey/4.2.3/about/history/) with minor bugfixes (would not help in your case, just to mention).

If you need dw 1.3 with guice 5, please look what issues are actual for you (except guice 5 compatibility ofc.) and I can release another bugfix version targeting guice 5. (write issues list here or in [discussion](https://github.com/xvik/dropwizard-guicey/discussions/183) directly).

**Comment by xvik** [comment]
Closing as inactive
