### ISSUE TITLE
java.lang.NoClassDefFoundError: jakarta/inject/Scope

### ISSUE THREAD

**Issue by Efgar** [xvik/dropwizard-guicey#430]
I am getting java.lang.NoClassDefFoundError: jakarta/inject/Scope after updating from 6.2.4 to 6.3.1, I think the line [here](https://github.com/xvik/dropwizard-guicey/blob/6.3.0/dropwizard-guicey/src/main/java/ru/vyarus/dropwizard/guice/module/installer/util/BindingUtils.java#L168) is to blame:

`if (annType.isAnnotationPresent(Scope.class) || annType.isAnnotationPresent(jakarta.inject.Scope.class)) {`

A missing import perhaps?

**Comment by xvik** [comment]
Sorry, I was unreachable. I will look this soon.

**Comment by xvik** [comment]
Guice 6 supports both javax.inject and jakarta.inject annotations, but jakarta.inject annotations are not present by default in the classpath. I was in hurry releasing all branches and missed that moment (jakarta annotations must be checked indirectly).

Also, yesterday maven central sunset its OSSRH publishing (which I was using), so I'll release bugfix version as soon as I switch to the new publication method
